project:
  type: website
  output-dir: docs

website:
  title: "PATHOME"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - dissemination.qmd
      - study_design.qmd
      - geotracking.qmd
      - about.qmd
      - contact_us.qmd
  back-to-top-navigation: true

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: left
    toc-title: ""


