project:
  type: website
  output-dir: docs

website:
  title: "PATHOME"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - people.qmd
      - dissemination.qmd
      - related_work.qmd
      - study_design.qmd
      - geotracking.qmd
      - contact_us.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: left
    toc-title: ""


