---
title: "Dissemination"
filters:
   - nutshell
format:
  html: 
    toc: false
---

## [:Baker, Kelly K., Sheillah Simiyu, Phylis Busienei, Fanta D. Gutema, Bonphace Okoth, John Agira, Christine S. Amondi, et al. 2023. “Protocol for the PATHOME Study: A Cohort Study on Urban Societal Development and the Ecology of Enteric Disease Transmission Among Infants, Domestic Animals and the Environment.” BMJ Open 13 (November): e076067.](#baker2024protocol)
Click [here](https://bmjopen.bmj.com/content/13/11/e076067) for the paper.

**ABSTRACT:**

Introduction. Global morbidity from enteric infections and diarrhoea remains high in children in low-income and middle-income countries, despite significant investment over recent decades in health systems and water and sanitation infrastructure. Other types of societal development may be required to reduce disease burden. Ecological research on the influence of household and neighbourhood societal development on pathogen transmission dynamics between humans, animals and the environment could identify more effective strategies for preventing enteric infections.

Methods and analysis. The ‘enteric pathome’—that is, the communities of viral, bacterial and parasitic pathogens transmitted from human and animal faeces through the environment is taxonomically complex in high burden settings. This integrated cohort-exposure assessment study leverages natural socioeconomic spectrums of development to study how pathome complexity is influenced by household and neighbourhood infrastructure and hygiene conditions. We are enrolling under 12-month-old children in low-income and middle-income neighbourhoods of two Kenyan cities (Nairobi and Kisumu) into a ‘short-cohort’ study involving repeat testing of child faeces for enteric pathogens. A mid-study exposure assessment documenting infrastructural, behavioural, spatial, climate, environmental and zoonotic factors characterises pathogen exposure pathways in household and neighbourhood settings. These data will be used to inform and validate statistical and agent-based models (ABM) that identify individual or combined intervention strategies for reducing multipathogen transmission between humans, animals and environment in urban Kenya.

Ethics and dissemination. The protocols for human subjects’ research were approved by Institutional Review Boards at the University of Iowa (ID-202004606) and AMREF Health Africa (ID-ESRC P887/2020), and a national permit was obtained from the Kenya National Commission for Science Technology and Innovation (ID# P/21/8441). The study was registered on Clinicaltrials.gov (Identifier: NCT05322655) and is in pre-results stage. Protocols for research on animals were approved by the University of Iowa Animal Care and Use Committee (ID 0042302).

---

## [:Busienei, Phylis J., Sheillah Simiyu, Daniel K. Sewell, Abisola Osinuga, and Kelly K. Baker. 2024. “Development of a Protocol for Using Geo-Trackers to Identify Zoonotic Enteric Pathogen Transmission Pathways in a Pilot Study in Kenya.” CABI One Health.](#busienei2024development)
Click [here](https://doi.org/10.1079/cabionehealth.2024.0011) for the paper.

**ABSTRACT:**
Humans and animals can be exposed to fecally-transmitted pathogens in both private and public domain environments. Animals may also acquire pathogen infections from these two environments and transmit them to humans through different pathways. Evidence on how often and where interactions occur between the two environments could improve the effectiveness of public health programs for preventing zoonotic disease transmission and response to disease outbreaks. This study aimed to develop a protocol for using geo-trackers to measure the spatial-temporal movement and interaction between animals and children in households and public areas in low- and middle-income categories of urban neighbourhoods in Kenya. It also aimed to identify opportunities and challenges for the scale-up of these methods’ for surveillance of other zoonotic diseases of public health significance. One commercial geo-tracker device with the best technological performance and usability that met pre-defined criteria for the study context was identified. Community engagement meetings were then conducted to gather input on a proposed study protocol. Afterwards, infants and animals were geo-tracked in 10 households in urban informal settlements of Kibera and Jericho, Nairobi over two consecutive weeks with iterative improvements to protocols. The effectiveness of the geo-tracking exercise was evaluated through in-depth interviews with Community Health Volunteers (CHVs) and infant caregivers. Animal and infant behaviour and battery reliability of the geo-trackers were also monitored; and observed opportunities and challenges in implementing the protocol during the exercise were documented. Community members were receptive and accepted the use of geo-trackers on animals and children. In pilot testing, there was no change of behaviour from 10 infants tracked. Discomfort was observed for up to 30 min after the placement for some of the seven animals tracked, but the animals quickly adjusted. The battery for all geo-tracker devices lasted for the 24-h geo-tracking period. Some caregivers and CHVs were concerned whether the geo-trackers could record personal information. It was shown that geo-tracker devices can be successfully deployed to study animal-child interactions and movement in different categories of urban neighbourhoods. Recommendations have been made on the lessons learnt from the study to help scientists who would use geo-trackers for future community-based human and animal research.

---


## [:Gutema, Fanta D., Bonphace Okoth, John Agira, Christine S. Amondi, Phylis J. Busienei, Sheillah Simiyu, Blessing Mberu, Daniel Sewell, and Kelly K. Baker. 2024. “Spatial-Temporal Patterns in the Enteric Pathogen Contamination of Soil in the Public Environments of Low- and Middle-Income Neighborhoods in Nairobi, Kenya.” International Journal of Environmental Research and Public Health 21.](#gutema2024spatial)
Click [here](https://www.mdpi.com/2994118) for the paper.

**ABSTRACT:**
Public spaces in countries with limited societal development can be contaminated with feces containing pathogenic microbes from animals and people. Data on contamination levels, spatial distribution, and the diversity of enteric pathogens in the public settings of low- and middle-income neighborhoods are crucial for devising strategies that minimize the enteric infection burden. The objective of this study was to compare spatial–temporal differences in the detection rate and diversity of enteric pathogens in the public spaces of low- and middle-income neighborhoods of Nairobi, Kenya. TaqMan array card (TAC) molecular assays were employed to analyze soil samples for 19 enteropathogens, along with a selective bacterial culture for pathogenic Enterobacteriaceae. An observational assessment was conducted during every site visit to document the hygienic infrastructure and sanitation conditions at the sites. We detected at least one pathogen in 79% (127/160) and ≥2 pathogens in 67.5% (108/160) of the soil samples tested. The four most frequently detected pathogens were EAEC (67.5%), ETEC (59%), EPEC (57.5%), and STEC (31%). The detection rate (91% vs. 66%) and mean number of enteric pathogens (5 vs. 4.7) were higher in low-income Kibera than in middle-income Jericho. The more extensive spatial distribution of pathogens in Kibera resulted in increases in the detection of different enteric pathogens from within-site (area < 50 m2) and across-site (across-neighborhood) movements compared to Jericho. The pathogen detection rates fluctuated seasonally in Jericho but remained at sustained high levels in Kibera. While better neighborhood conditions were linked with lower pathogen detection rates, pathogenic E. coli remained prevalent in the public environment across both neighborhoods. Future studies should focus on identifying how the sources of pathogen contamination are modified by improved environmental sanitation and hygiene and the role of these contaminated public environments in enteric infections in children.

---




## [:Mberu, Blessing, Sheillah Simiyu, Fanta D Gutema, Daniel Sewell, Phylis J Busienei, Innocent K Tumwebaze, and Kelly K Baker. 2024. “Landscape Analysis of the Kenyan Policy on the Treatment and Prevention of Diarrheal Disease Among Under-5 Children.” BMJ Open 14 (8).](#mberu2024landscape)
Click [here](https://doi.org/10.1136/bmjopen-2023-081906) for the paper.

**ABSTRACT:**
Objective. Diarrhoea remains a leading cause of morbidity and death among under-5 children in Kenya, despite multipronged policy and programme initiatives to increase access to treatment. This study interrogates the comprehensiveness and adequacy of Kenya’s policies, frameworks and action plans for diarrheal management and prevention. The study seeks to identify policy and practice gaps that need to be filled to strengthen diarrhoea treatment and prevention among under-5 children in Kenya.

Design. Our study is a landscape analysis, which seeks to identify the gaps in the current Kenya diarrheal policy, frameworks and action plans. The critical questions included their comprehensiveness, the availability of elaborate treatment, management and prevention solutions, together with updatedness, building on evidence from extant literature on key pathways to infection relating to man-animal environmental interaction, which are critical in enteric infection prevention initiatives.

Data sources. We conducted an internet search of databases of Government of Kenya’s Ministry of Health; relevant websites/publications of international organisations and groups (Centre for Disease Control and Prevention, UNICEF and WHO) and published and grey literature (Google searches, Google Scholar and PubMed).

Eligibility criteria. Included are publicly available key national diarrheal policy frameworks, plans, strategies, laws, institutional frameworks and operational guidelines that inform pertinent questions on the adequacy of policy and practice and preventive policy updates and actions. Further, peer-reviewed and grey literature on diarrheal morbidity and mortality and diarrheal prevention and management are included. The analysis excluded any information that was not referenced on the internet nor obtained from the internet.

Data extraction and synthesis. The review team extracted the key provisions of the policy guidelines guided by a checklist and questions around the adequacy of existing national policies in addressing the determinants, prevention and treatment interventions of enteric infections and diarrhoea among under-5 children in the country. The checklist covered Kenyan background and diarrhoea situation analysis, policy objectives, policy strategies and policy implementation.

Results. The analysis identified a corpus of strategies for the management of diarrhoea at multiple levels: health facilities, communities and households. The policies highlighted advocacy, health communication and social mobilisation, as well as logistics management and prevention strategies. However, the triangulation of evidence from the policy provisions and extant literature identified critical policy gaps in diarrhoea prevention and management in Kenya, particularly the lack of focus on zoonotic pathways to enteric infection, environment-pathogen linkages and operationalisation of the roles of social determinants of health and related services. The policy documents had limited focus on rapid diagnosis, vaccine development and deployment, together with weak funding commitment towards implementation and unclear pathways to funding responsibilities.

Conclusion. Policies are central to guiding programmatic actions towards effective enteric and diarrhoea prevention and management measures in Kenya. This study shows the need for policy updates to reflect pathways to enteric infections not covered in the current policy guidelines. Further, there is a need to strengthen the treatment and management of infection through rapid diagnosis, vaccine development and deployment, and strong funding commitment towards implementation together with clear funding responsibilities. Together, these will be vital in strengthening the current policy provisions and addressing other pathways to the prevention of enteric infections relating to zoonotic, environment-pathogen linkages and social determinants of health in Kenya and other low-income and middle-income countries.

---



## [:Sewell, Daniel K., and Kelly K. Baker. 2024. “Estimating Risk Factors for Pathogenic Dose Accrual from Longitudinal Data.”](#sewell2024estimating)
Click [here](https://arxiv.org/abs/2407.20051) for the paper.

**ABSTRACT:**
Estimating risk factors for incidence of a disease is crucial for understanding its etiology. For diseases caused by enteric pathogens, off-the-shelf statistical model-based approaches do not consider the biological mechanisms through which infection occurs and thus can only be used to make comparatively weak statements about association between risk factors and incidence. Building off of established work in quantitative microbiological risk assessment, we propose a new approach to determining the association between risk factors and dose accrual rates. Our more mechanistic approach achieves a higher degree of biological plausibility, incorporates currently-ignored sources of variability, and provides regression parameters that are easily interpretable as the dose accrual rate ratio due to changes in the risk factors under study. We also describe a method for leveraging information across multiple pathogens. The proposed methods are available as an R package at <a href = "https://github.com/dksewell/dare">https://github.com/dksewell/dare</a>. Our simulation study shows unacceptable coverage rates from generalized linear models, while the proposed approach empirically maintains the nominal rate even when the model is misspecified. Finally, we demonstrated our proposed approach by applying our method to infant data obtained through the PATHOME study (<a href="https://reporter.nih.gov/project-details/10227256">https://reporter.nih.gov/project-details/10227256</a>), discovering the impact of various environmental factors on infant enteric infections.

---



## [:Baker, Kelly K, Jane Awiti Odhiambo Mumma, Sheillah Simiyu, Daniel Sewell, Kevin Tsai, John David Anderson, Amy MacDougall, Robert Dreibelbis, and Oliver Cumming. 2022. “Environmental and Behavioural Exposure Pathways Associated with Diarrhoea and Enteric Pathogen Detection in 5-Month-Old, Periurban Kenyan Infants: A Cross-Sectional Study.” BMJ Open 12 (10)](#baker2022environmental)
Click [here](https://doi.org/10.1136/bmjopen-2021-059878) for the paper.

**ABSTRACT:**
Objectives. The aim of this study was to test whether household environmental hygiene and behavioural conditions moderated associations between diarrhoea and enteric pathogen detection in infants 5 months of age in Kenya and pathogen sources, including latrine access, domestic animal co-habitation and public food sources.

Design. Cross-sectional study utilising enrolment survey data of households participating in the Safe Start cluster-randomised controlled trial .

Setting. Kisumu, Kenya.

Participants. A total of 898 caregivers with 5-month (22 week ± 1 week) aged infants were enrolled in the study and completed the enrolment survey.

Primary and secondary outcome measures. Outcomes were (1) caregiver-reported 7-day diarrhoea prevalence and (2) count of types of enteric viruses, bacteria and parasites in infant stool. Exposures and effect modifiers included water access and treatment, cohabitation with domestic animals, sanitation access, handwashing practices, supplemental feeding, access to refrigeration and flooring.

Results. Reported handwashing after handling animals (adjusted odds ratio (aOR)=0.20; 95% CI=0.06 to 0.50) and before eating (aOR=0.44; 95% CI=0.26 to 0.73) were strongly associated with lower risk of caregiver-reported diarrhoea, while cohabitation with animals (aOR=1.54; 95% CI=1.01 to 2.34) living in a household with vinyl-covered dirt floors (aOR=0.60; 95% CI=0.45 to 0.87) were strongly associated with pathogen codetection in infants. Caregiver handwashing after child (p=0.02) or self-defecation (p=0.03) moderated the relationship between shared sanitation access and infant exposure to pathogens, specifically private latrine access was protective against pathogen exposure of infants in households, where caregivers washed hands after defecation. In the absence of handwashing, access to private sanitation posed no benefits over shared latrines for protecting infants from exposure.

Conclusion. Our evidence highlights eliminating animal cohabitation and improving flooring, postdefecation and food-related handwashing, and safety and use of cow milk sources as interventions to prevent enteric pathogen exposure of young infants in Kenya.

---


## [:Baker, Kelly K., Reid Senesac, Daniel K. Sewell, Ananya Sen Gupta, Oliver Cumming, and Jane Mumma. 2018. “Fecal Fingerprints of Enteric Pathogen Contamination in Low-Income Neighborhoods of Kisumu, Kenya: The Role of Human and Domestic Animal Sources in Environmental Pathogen Contamination Patterns.” Environmental Science & Technology 52 (18): 10263–74.](#baker2018fecal)
Click [here](https://doi.org/10.1021/acs.est.8b01528) for the paper.

**ABSTRACT:**
Young children are infected by a diverse range of enteric pathogens in high disease burden settings, suggesting pathogen contamination of the environment is equally diverse. This study aimed to characterize across- and within-neighborhood diversity in enteric pathogen contamination of public domains in urban informal settlements of Kisumu, Kenya, and to assess the relationship between pathogen detection patterns and human and domestic animal sanitation conditions. Microbial contamination of soil and surface water from 166 public sites in three Kisumu neighborhoods was measured by enterococcal assays and quantitative reverse transcription polymerase chain reaction (qRT-PCR) for 19 enteric pathogens. Regression was used to assess the association between observed sanitary indicators of contamination with enterococci and pathogen presence and concentration, and pathogen diversity. Seventeen types of pathogens were detected in Kisumu public domains. Enteric pathogens were codetected in 33% of soil and 65% of surface water samples. Greater pathogen diversity was associated with the presence of domestic animal feces but not with human open defecation, deteriorating latrines, flies, or disposal of human feces. Sanitary conditions were not associated with enterococcal bacteria, specific pathogen concentrations, or “any pathogen”. Young children played at 40% of observed sites. Managing domestic animal feces may be required to reduce enteric pathogen environmental contamination in high-burden settings.



---



## [:Gutema, Fanta D., Oliver Cumming, Jane Mumma, Sheillah Simiyu, Edwin Attitwa, Bonphace Okoth, John Denge, Daniel Sewell, and Kelly K. Baker. 2024. “Enterococcus Contamination of Infant Foods and Implications for Exposure to Food-Borne Pathogens in Peri-Urban Neighborhoods of Kisumu, Kenya.” Epidemiology and Infection, 1–32.](#gutema2024enterococcus)
Click [here](https://doi.org/10.1017/S0950268824000062) for the paper.

**ABSTRACT:**
We collected infant food samples from 714 households in Kisumu, Kenya, and estimated the prevalence and concentration of Enterococcus, an indicator of food hygiene conditions. In a subset of 212 households, we quantified the change in concentration in stored food between a morning and afternoon feeding time. In addition, household socioeconomic characteristics and hygiene practices of the caregivers were documented. The prevalence of Enterococcus in infant foods was 50% (95% confidence interval: 46.1 - 53.4), and the mean log10 colony-forming units (CFUs) was 1.1 (SD + 1.4). No risk factors were significantly associated with the prevalence and concentration of Enterococcus in infant foods. The mean log10 CFU of Enterococcus concentration was 0.47 in the morning and 0.73 in the afternoon foods with a 0.64 log10 mean increase in matched samples during storage. Although no factors were statistically associated with the prevalence and the concentration of Enterococcus in infant foods, household flooring type was significantly associated with an increase in concentration during storage, with finished floors leading to 1.5 times higher odds of concentration increase compared to unfinished floors. Our study revealed high prevalence but low concentration of Enterococcus in infant food in low-income Kisumu households, although concentrations increased during storage implying potential increases in risk of exposure to foodborne pathogens over a day. Further studies aiming at investigating contamination of infant foods with pathogenic organisms and identifying effective mitigation measures are required to ensure infant food safety.



---


## [:Hoffmann, Vivian, Sheillah Simiyu, Daniel K. Sewell, Kevin Tsai, Oliver Cumming, Jane Mumma, and Kelly K. Baker. 2022. “Milk Product Safety and Household Food Hygiene Influence Bacterial Contamination of Infant Food in Peri-Urban Kenya.” Frontiers in Public Health 9.](#hoffman2022milk)
Click [here](https://doi.org/10.3389/fpubh.2021.772892) for the paper.

**ABSTRACT:**
Background: Milk is a common infant food in peri-urban Kenya that can transmit diarrhea-causing enteric pathogens. Little is known about how contamination of milk at point of purchase and household handling of milk-based infant foods contribute to infant exposure to enteric pathogens.

Objective: To compare the prevalence and concentrations of bacterial indicator organisms and enteric pathogens in unpackaged, fresh pasteurized, and ultra-high temperature (UHT) treated milk at purchase and assess the influence of the type of milk used to prepare infant food on contamination of this food.

Methods: Paired samples of purchased milk and infant food prepared with this milk were obtained from 188 households in low-income neighborhoods in Kisumu, Kenya. Samples were cultured on selective media to isolate Salmonella enterica, Shigella spp., Klebsiella aerogenes, Proteus spp., and Escherichia coli, with pathogens validated by PCR. Probability of detection of these bacteria was compared by milk product treatment and packaging method, and between milk at point of purchase vs. food at point of infant consumption.

Results: Unpackaged milk was most contaminated at point of purchase, but bacterial contamination was also present in pasteurized and UHT milk at purchase. Presence of bacteria in UHT and fresh pasteurized milk at purchase predicted presence of the same bacteria type in infant food. Prevalence of bacterial contamination and concentration level for bacterial indicators generally increased between point of purchase and consumption in UHT and fresh pasteurized milk-based food but decreased in unpackaged milk-based food. Prevalence of the four fecal bacteria were similar in infant foods prepared with each type of milk.

Conclusion: Both pre-market contamination and post-purchase handling influence the likelihood of infants ingesting foods contaminated by diarrheal pathogens.



---


## [:Houser, Daniel K. AND Medgyesi, Stephanie A. AND Sewell. 2024. “A Multi-Pathogen Behavioral Exposure Model for Young Children Playing in Public Spaces in Developing Communities.” PLOS Neglected Tropical Diseases 18 (10): 1–20.](#houser2024multipathogen)
Click [here](https://doi.org/10.1371/journal.pntd.0012564) for the paper.

**ABSTRACT:**
Diarrheal disease is the second leading cause of death among children under five in developing communities, despite active interventions to improve access to water, sanitation, and hygiene resources. Even interventions with high fidelity and compliance saw minimal improvements in health outcomes, necessitating a need for looking beyond traditionally targeted exposure pathways. This study focuses on the pathogen exposure a young child may receive while playing in the public spaces of informal settlements, where animal feces, human feces, and garbage are frequently observed. The study utilized 79 soil samples previously collected across ten cluster sites in Corail, Haiti and processed using DelAgua cultural assays and quantitative Polymerase Chain Reaction methods. Molecular assays screened for Aeromonas, Vibrio cholera, and several pathogenic Escherichia coli species. Behavioral observations of young children (<5 years old) were also conducted in overlapping areas with the environmental sampling to quantify frequency of risky and mitigating behaviors. Environmental and behavioral data were combined to obtain the posterior distribution of children’s pathogen exposure from playing in a public space for one hour. The model estimated that children have a likelihood of approximately 70% of being exposed to a pathogen during one hour of play and a greater than 30% chance of being exposed to multiple pathogens in the same period. While children and toddlers practice fewer risky behaviors compared to infants, they were shown to have higher likelihood of exposure and slightly higher pathogen dose per exposure. As anticipated, a high correlation between genes from the same E. coli species was observed in the model output. These findings demonstrate the need to consider public spaces as an important exposure pathway for young children for both future research and interventions.



---


## [:Medgyesi, Danielle N, John M. Brogan, Daniel K Sewell, Jean Philippe Creve-Coeur, Laura H Kwong, and Kelly K Baker. 2018. “Where Children Play: Young Child Exposure to Environmental Hazards During Play in Public Areas in a Transitioning Internally Displaced Persons Community in Haiti.” International Journal of Environmental Research and Public Health 15 (8): 1646. ](#baker2024protocol)
Click [here](https://doi.org/10.3390/ijerph15081646) for the paper.

**ABSTRACT:**
Globally, gastrointestinal (GI) infections by enteric pathogens are the second-leading cause of morbidity and mortality in children under five years of age (≤5 years). While GI pathogen exposure in households has been rigorously examined, there is little data about young children’s exposure in public domains. Moreover, public areas in low-income settings are often used for other waste disposal practices in addition to human feces, such as trash dumping in areas near households. If young children play in public domains, they might be exposed to interrelated and highly concentrated microbial, chemical, and physical hazards. This study performed structured observations at 36 public areas in an internally displaced persons community that has transitioned into a formal settlement in Haiti. We documented how often young children played in public areas and quantified behaviors that might lead to illness and injury. Children ≤5 years played at all public sites, which included infants who played at 47% of sites. Children touched and mouthed plastic, metal and glass trash, food and other objects from the ground, ate soil (geophagia) and drank surface water. They also touched latrines, animals, animal feces and open drainage canals. Hand-to-mouth contact was one of the most common behaviors observed and the rate of contact significantly differed among developmental stages (infants: 18/h, toddlers: 11/h and young children: 9/h), providing evidence that children could ingest trace amounts of animal/human feces on hands that may contain GI pathogens. These findings demonstrate that water, sanitation and hygiene interventions could be more effective if they consider exposure risks to feces in public domains. Furthermore, this research highlights the need for waste-related interventions to address the broader set of civil conditions that create unsafe, toxic and contaminated public environments where young children play.



---


## [:Medgyesi, Danielle, Daniel K. Sewell, Reid Senesac, Oliver Cumming, Jane Mumma, and Kelly K. Baker. 2019. “The Landscape of Enteric Pathogen Exposure for Children During Play in Public Domains of Low-Income, Kisumu, Kenya.” PLOS Neglected Tropical Diseases 13 (3): e0007292.](#medgyesi2019landscape)
Click [here](https://doi.org/10.1371/journal.pntd.0007292) for the paper.

**ABSTRACT:**
Young children are infected by a diverse variety of enteric pathogens in low-income, high-burden countries. Little is known about which conditions pose the greatest risk for enteric pathogen exposure and infection. Young children frequently play in residential public areas around their household, including areas contaminated by human and animal feces, suggesting these exposures are particularly hazardous. The objective of this study was to examine how the dose of six types of common enteric pathogens, and the probability of exposure to one or multiple enteric pathogens for young children playing at public play areas in Kisumu, Kenya is influenced by the type and frequency of child play behaviors that result in ingestion of soil or surface water. Additionally, we examine how pathogen doses and multi-pathogen exposure are modified by spatial variability in the number of public areas children are exposed to in their neighborhood. A Bayesian framework was employed to obtain the posterior distribution of pathogen doses for a certain number of contacts. First, a multivariate mixed effects tobit model was used to obtain the posterior distribution of pathogen concentrations, and their interdependencies, in soil and surface water, based upon empirical data of enteric pathogen contamination in three neighborhoods of Kisumu. Then, exposure doses were estimated using behavioral contact parameters from previous studies and contrasted under different exposure conditions. Pathogen presence and concentration in soil varied widely across local (< 25 meter radius area) and neighborhood-level scales, but pathogens were correlated among distinct surface water samples collected near to each other. Multi-pathogen exposure of children at public play areas was common. Pathogen doses and the probability of multi-pathogen ingestion increased with: higher frequency of environmental contact, especially for surface water; larger volume of soil or water ingested; and with play at multiple sites in the neighborhood versus single site play. Child contact with surface water and soil at public play areas in their neighborhood is an important cause of exposure to enteric pathogens in Kisumu, and behavioral, environmental, and spatial conditions are determinants of exposure.



---


